//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCMSEntities : DbContext
    {
        public CCMSEntities()
            : base("name=CCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationResources> ApplicationResources { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<GroupResources> GroupResources { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UsersLogs> UsersLogs { get; set; }
        public virtual DbSet<ComplaintsCategory> ComplaintsCategory { get; set; }
        public virtual DbSet<ComplaintsCategoryMatrix> ComplaintsCategoryMatrix { get; set; }
        public virtual DbSet<GroupResources_View> GroupResources_View { get; set; }
        public virtual DbSet<SLAViolationChecker_view> SLAViolationChecker_view { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SLAStatus_view> SLAStatus_view { get; set; }
        public virtual DbSet<User_View> User_View { get; set; }
        public virtual DbSet<CustomerComplaints> CustomerComplaints { get; set; }
    }
}
