//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationResources
    {
        public int Id { get; set; }
        public string ResouceName { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsCategory
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Notify { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsCategoryMatrix
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string SubCategory { get; set; }
        public string SLA { get; set; }
        public string InternalSLA { get; set; }
        public string CBNCode { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerComplaints
    {
        public int ID { get; set; }
        public string Tracking_Reference_Number { get; set; }
        public string Account_Branch_Name { get; set; }
        public string Name_Of_Consultant { get; set; }
        public string Type_Of_Client { get; set; }
        public string Name_Of_Complainant { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Unique_Identification_No { get; set; }
        public string Account_Number { get; set; }
        public string Account_Type { get; set; }
        public string Account_Currency { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Postal_Code { get; set; }
        public string Cell_Phone_Number { get; set; }
        public string Office_Number { get; set; }
        public string Complaint_Channel { get; set; }
        public string Complaint_Location_Branch { get; set; }
        public string Complaint_Location_City { get; set; }
        public string Email_Address { get; set; }
        public string Complaint_Category { get; set; }
        public string Complaint_Sub_Category { get; set; }
        public string Complaint_Sub_Category_Code { get; set; }
        public string Subject_Of_Complaint { get; set; }
        public string Complaint_Description { get; set; }
        public string Date_Received { get; set; }
        public string Date_Closed { get; set; }
        public string Description_of_Resolution { get; set; }
        public Nullable<decimal> Amount_In_Dispute { get; set; }
        public Nullable<decimal> Amount_Refunded_Petitioner { get; set; }
        public Nullable<decimal> Amount_Recovered_by_Bank { get; set; }
        public string Action_Taken { get; set; }
        public string Status_Of_Complaint { get; set; }
        public string Remarks_by_Bank { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modifiied { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public string Method { get; set; }
        public string LineNumber { get; set; }
        public string Message { get; set; }
        public string OtherInfo { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupResources
    {
        public int Id { get; set; }
        public int Group_Id { get; set; }
        public int ApplicationResource_Id { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupResources_View
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string Status { get; set; }
        public int Resource_Id { get; set; }
        public string ResouceName { get; set; }
        public string defaultpage { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLAStatus_view
    {
        public string Tracking_Reference_Number { get; set; }
        public string Account_Branch_Name { get; set; }
        public string Name_Of_Consultant { get; set; }
        public string Type_Of_Client { get; set; }
        public string Name_Of_Complainant { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Unique_Identification_No { get; set; }
        public string Account_Number { get; set; }
        public string Account_Type { get; set; }
        public string Account_Currency { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Postal_Code { get; set; }
        public string Cell_Phone_Number { get; set; }
        public string Office_Number { get; set; }
        public string Complaint_Channel { get; set; }
        public string Complaint_Location_Branch { get; set; }
        public string Email_Address { get; set; }
        public string Complaint_Sub_Category_Code { get; set; }
        public string Subject_Of_Complaint { get; set; }
        public string Complaint_Description { get; set; }
        public string Date_Received { get; set; }
        public string Date_Closed { get; set; }
        public Nullable<decimal> Amount_In_Dispute { get; set; }
        public Nullable<decimal> Amount_Refunded_Petitioner { get; set; }
        public Nullable<decimal> Amount_Recovered_by_Bank { get; set; }
        public string Action_Taken { get; set; }
        public string Status_Of_Complaint { get; set; }
        public string Remarks_by_Bank { get; set; }
        public string Date_Created { get; set; }
        public string Created_By { get; set; }
        public string Supervisor_email { get; set; }
        public string Date_Modifiied { get; set; }
        public string Modified_By { get; set; }
        public string CBN_SLA_Limit_in_days { get; set; }
        public string Internal_Limit_in_days { get; set; }
        public string SLA_STATUS { get; set; }
        public string Complaint_Category { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLAViolationChecker_view
    {
        public string Tracking_Reference_Number { get; set; }
        public string Name_Of_Complainant { get; set; }
        public string Subject_Of_Complaint { get; set; }
        public string Complaint_Description { get; set; }
        public string Date_Received { get; set; }
        public string Account_Branch_Name { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_By { get; set; }
        public string Supervisor_email { get; set; }
        public Nullable<System.DateTime> Date_Modifiied { get; set; }
        public string Modified_By { get; set; }
        public string CBN_SLA_Limit { get; set; }
        public string Internal_Limit { get; set; }
        public Nullable<int> DateDiff { get; set; }
        public string SLA_STATUS { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_View
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string UserStatus { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public string GroupName { get; set; }
        public string GroupStatus { get; set; }
        public string defaultpage { get; set; }
        public string UserType { get; set; }
        public string CategoryName { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string Status { get; set; }
        public string defaultpage { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string SessionID { get; set; }
        public string Supervisor_id { get; set; }
        public string Supervisor_email { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public string UserType { get; set; }
        public string Branch { get; set; }
        public string TeamEmail { get; set; }
        public string CategoryName { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLogs
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserRole { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public bool isLoggedIn { get; set; }
    }
}
